# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0353807710017130c8822b8264a73dd591de7832b0d45a9fe5cd43cf1d805968d353673e5f3374201f3070f7e7efd86f4c6f1441b6da346de3298aa50088a542

test:
  secret_key_base: 3c73a49963e1f3679df406e23aa1cd580691a79e9a1e1809c636d634e5c032589a8a692203df42f60d400d7e7f2d355a8943359e92becb5ee1492eccaa7575f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
